### ISSUE TITLE
Research on Human-AI Communication/Collaboration

### ISSUE THREAD

**Issue by LJArendse** [gameaischool2021members/change#12]

**Comment by ChristianCecconi** [comment]
https://www.aaai.org/AAAI21Papers/AAAI-8636.BansalG.pdf

https://scholarspace.manoa.hawaii.edu/bitstream/10125/70652/0035.pdf

https://dl.acm.org/doi/abs/10.1145/3415167

https://arxiv.org/abs/2105.11000

https://www.nature.com/articles/d41586-021-01170-0

**Comment by LJArendse** [comment]
Nice :100:

**Comment by LJArendse** [comment]
@ChristianCecconi Nice work. Issue completed with commit 9a41262bce93acb7271955735db5e15075943c98.
